### ISSUE TITLE
1,21,1

### ISSUE THREAD

**Issue by OneWorldStudio** [Blobanium/MCBrowser#14]
![image](https://github.com/user-attachments/assets/0e79c15b-a030-4b7b-b8c4-3a9f93ea9de6)
![image](https://github.com/user-attachments/assets/086fd941-9ebb-418f-b3e5-2a6bd815a5fd)

**Comment by Blobanium** [comment]
Seems like MCEF doesn't support 1.21.1 just yet, I could make a PR within MCEF as there isn't really much that changed going from 1.21 to 1.21.1.

**Comment by OneWorldStudio** [comment]
Thanks

**Comment by Blobanium** [comment]
https://modrinth.com/mod/mcef/version/Ch5GGmc9

**Comment by OneWorldStudio** [comment]
thanks so much
