### ISSUE TITLE
Resource pack menu "Open Pack Folder" button opens folder location inside internal MCBrowser instead of external file program

### ISSUE THREAD

**Issue by BlueJayofEvil** [Blobanium/MCBrowser#16]
Minecraft 1.21.1
Fabric Loader 0.16.7
MCBrowser 1.1.3
MCEF 2.1.5

Title is self-explanatory. I reduced my modpack to a smaller minimal fresh instance to reduce possible conflicts.
Here's what happens when you click the "Open Pack Folder" button:
![2024-10-14_21 00 48](https://github.com/user-attachments/assets/d0dc121e-3fc0-4746-9390-1393345d6d31)

Logs: https://mclo.gs/DuEcxea

**Comment by Blobanium** [comment]
1.1.4 has been released that fixes this issue

https://modrinth.com/mod/mcbrowser/version/1.1.4
https://github.com/Blobanium/MCBrowser/releases/tag/v1.1.4
