### ISSUE TITLE
MCBrowser redirects into itself.

### ISSUE THREAD

**Issue by LPFan12** [Blobanium/MCBrowser#17]
The config option "Open Links in MCBrowser" set to true makes the button "Open in external browser" open the requested tab in MCBrowser again, instead of an actual external browser. This is *technically* not incorrect because the config option does what it says on the tin, but it is both unhelpful and unintuitive due to what the button says. 

If I press the button, then I already opened the link in MCBrowser and wish to open it in another browser(most likely for missing features like inputting a @ or copying text with a right click), so it should be a very safe change to just make an exception for the button's function to not be redirected.

**Comment by Blobanium** [comment]
https://github.com/Blobanium/MCBrowser/releases/tag/v1.1.5
